CREATE CONSTRAINT ON (model:Model) ASSERT model.id IS UNIQUE
CREATE CONSTRAINT ON (uniqueid:UniqueId) ASSERT uniqueid.name IS UNIQUE
CREATE CONSTRAINT ON (user:User) ASSERT user.lowerUsername IS UNIQUE
CREATE CONSTRAINT ON (user:User) ASSERT user.email IS UNIQUE
CREATE CONSTRAINT ON (group:Group) ASSERT group.lowerName IS UNIQUE